FROM rhel8:latest

RUN dnf update -y && \
    dnf install -y openstack-ironic-python-agent lshw smartmontools iproute python-hardware && \
    dnf clean all

# NOTE(TheJulia/juliakreger): this command defaults to using multicast
# dns lookups.
ENTRYPOINT ["/usr/bin/ironic-collect-introspection-data", "--introspection_daemon"]
