FROM rhel8:latest

RUN yum update -y && \
    yum install -y openstack-ironic-python-agent lshw smartmontools && \
    yum clean all

# NOTE(TheJulia/juliakreger): this command defaults to using multicast
# dns lookups.
ENTRYPOINT ["/usr/bin/ironic-collect-introspection-data", "--introspection_daemon"]
